Email validation fix
red-gate/honeycomb-web-toolkit pull request #172
Opened 2020-10-02 13:33 UTC by DaveConvery

This is additional validation using Salesforce's own regex to match their email rules: https://developer.salesforce.com/docs/atlas.en-us.noversion.mc-apis.meta/mc-apis/using_regular_expressions_to_validate_email_addresses.htm

I've tested this with quite a few email addresses and the main issue I can see is that it flatly rejects emails with uppercase characters. Since email addresses should be (largely) case-insensitive this feels like overkill.

We could:

- Run with it (maybe expand the error message?) since there's some value to it
- Just pass through a lowercase version of whatever's typed into the test
- Strip that validation out of the regex (feels like there's probably value in matching SFDC exactly for maintainability)

What do people think?

2020-10-06 15:32 UTC, philscott-rg approved these changes
This looks good! And it handles the `.` character in the username like we hoped

> Just pass through a lowercase version of whatever's typed into the test

I think this sounds like the best way round the case-sensitivity

2020-10-06 15:33 UTC, philscott-rg requested changes
updating this to 'request changes' because I guess the case-sensitivity thing still needs to go in before it's merged

2020-10-06 15:58 UTC, DaveConvery commented
I've added that and tested it against ALL CAPS

2020-10-06 16:02 UTC, philscott-rg approved these changes

2020-10-06 16:12 UTC, DaveConvery commented
Thanks - will merge and deploy tomorrow so we can keep an eye on it.

2020-10-07 06:36 UTC, edwardcasbon approved these changes

2020-10-07 08:00 UTC, merged