Marketo form scroll to error
red-gate/honeycomb-web-toolkit pull request #173
Opened 2020-10-08 09:48 UTC by DaveConvery

Per https://github.com/red-gate/website-static/pull/1516, this adds scroll to (the highest available) error on submission. I've made this a jump rather than a smooth scroll because I have a feeling that's going to be less annoying when trying to submit a form.

2020-10-08 17:29 UTC, philscott-rg requested changes
At the moment this gets covered if you're on a page with a sticky nav

The best way round this might be to use the `scrollIntoView` option for aligning the target element in the vertical center of the viewport:
`scrollIntoView({ behavior: 'smooth', block: 'center' });`

![image](https://user-images.githubusercontent.com/5636866/95493054-d434ba80-0993-11eb-9c6f-9578a6e7c9b3.png)

2020-10-09 06:50 UTC, edwardcasbon commented
There's no support for `scrollIntoView` for Safari or IE, however there is for the other browsers, so I think it's a suitable improvement for those that are using supported browsers.

2020-10-12 08:01 UTC, DaveConvery commented
I've made that change. FWIW it's working fine for me in Safari, so it might just be IE users who are left behind. But they're used to that.

2020-10-12 08:13 UTC, edwardcasbon approved these changes

2020-10-12 08:13 UTC, merged